name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Fly.io Docker Registry
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo $FLY_API_TOKEN | docker login registry.fly.io -u $USER --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest .
          docker push registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.2
        with:
          args: "deploy --image registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest --config ./fly.toml"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
